# Generated by Django 4.2 on 2024-06-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="оплачено"),
        ),
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="идентификатор сессии",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_status",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="статус оплаты"
            ),
        ),
    ]
